In [31]:
import pandas as pd
import numpy as np
import pickle 
import matplotlib.pyplot as plt 
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

In [43]:
df = pd.read_csv('taxi.csv')
df.head()

Priceperweek  Population  Monthlyincome  Averageparkingpermonth  \
0            15     1800000           5800                      50   
1            15     1790000           6200                      50   
2            15     1780000           6400                      60   
3            25     1778000           6500                      60   
4            25     1750000           6550                      60   

   Numberofweeklyriders  
0                192000  
1                190400  
2                191200  
3                177600  
4                176800

In [44]:
df_x = df.iloc[:,0:-1].values
df_y = df.iloc[:,-1].values

In [45]:
df_x

array([[     15, 1800000,    5800,      50],
       [     15, 1790000,    6200,      50],
       [     15, 1780000,    6400,      60],
       [     25, 1778000,    6500,      60],
       [     25, 1750000,    6550,      60],
       [     25, 1740000,    6580,      70],
       [     25, 1725000,    8200,      75],
       [     30, 1725000,    8600,      75],
       [     30, 1720000,    8800,      75],
       [     30, 1705000,    9200,      80],
       [     30, 1710000,    9630,      80],
       [     40, 1700000,   10570,      80],
       [     40, 1695000,   11330,      85],
       [     40, 1695000,   11600,     100],
       [     40, 1690000,   11800,     105],
       [     40, 1630000,   11830,     105],
       [     65, 1640000,   12650,     105],
       [    102, 1635000,   13000,     110],
       [     75, 1630000,   13224,     125],
       [     75, 1620000,   13766,     130],
       [     75, 1615000,   14010,     150],
       [     80, 1605000,   14468,     155],
       [  

In [46]:
df_y

array([192000, 190400, 191200, 177600, 176800, 178400, 180800, 175200,
       174400, 173920, 172800, 163200, 161600, 161600, 160800, 159200,
       148800, 115696, 147200, 150400, 152000, 136000, 126240, 123888,
       126080, 151680, 152800], dtype=int64)

In [54]:
 X_train, X_test, y_train, y_test = train_test_split(df_x,df_y,test_size=0.3,random_state=0)

In [55]:
reg = LinearRegression()
reg.fit(X_train,y_train)

LinearRegression()

In [56]:
reg.score(X_train,y_train)

0.9428364724316812

In [57]:
reg.score(X_test,y_test)

0.9157379222488218

In [58]:
pickle.dump(reg,open('text.pkl','wb'))

In [59]:
model = pickle.load(open('text.pkl','rb'))

In [60]:
model.predict([[80,2000000,10000,100]])

array([185006.64539404])

In [61]:
model.predict([[15,1700000,5000,55]])

array([177679.90453909])